Resources:
  ServerlessTodoRdsCluster:
    Type: AWS::RDS::DBCluster
    Properties: 
      DatabaseName: serverless_todo
      DBClusterIdentifier: serverless-Todo-rds-cluster
      DBClusterParameterGroupName:
         Ref: ServerlessTodoRdsClusterParameter
      # DBSubnetGroupName: String   # need to update it
      Engine: "aurora-mysql"
      EngineVersion: "5.7.mysql_aurora.2.07.1"
      MasterUsername: ${env:RDS_USERNAME}_${env:STAGE}  
      MasterUserPassword: ${env:DB_PASSWORD}
      ScalingConfiguration:
        AutoPause: true
        MinCapacity: 1
        MaxCapacity: 8
        SecondsUntilAutoPause: "1000"
  
  ServerlessTodoRdsInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: aurora-mysql-instance1
      Engine: "aurora-mysql"
      EngineVersion: "5.7.mysql_aurora.2.07.1"
      DBClusterIdentifier:
        Ref: ServerlessTodoRdsCluster
      PubliclyAccessible: 'true'
      DBInstanceClass: db.t2.micro
    
  ServerlessTodoRdsClusterParameter:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: Parameter group for the Serverless Aurora RDS DB.
      Family: "aurora-mysql8.0"
      Parameters:
        character_set_database: "utf8"

  ServerlessTodoRdsClusterParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: Parameter group for the Serverless Aurora RDS DB.
      Family: "aurora-mysql8.0"
      Parameters:
        sql_mode: IGNORE_SPACE
        max_connections: 100
        wait_timeout: 900
        interactive_timeout: 900
