Resources:
  ServerlessTemplateRole:
    Type: AWS::IAM::Role
    Properties:
      Description: This is an example role for SLS todo
      RoleName: ${self:service}-todo
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole

  AccessRDSPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Managed policy to provide access to the RDS
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action:
              - rds:*
            Resource: '*'

  LambdaRDSRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:service}-${sls:stage}-lambda-ddb-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com

  ServerlessTemplateSQSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - !Sub
          - 'arn:aws:sqs:${Region}:${AccountId}::local_todo.fifo.*'
          - Region: ${aws:region}
            AccountId: ${aws:accountId}
