module.exports = {
	collectCoverageFrom: [
		'./**/*.js',
		'!babel.config.js',
		'!.eslintrc.js',
		'!jest.config.js',
		'!webpack.config.js',
		'!coverage/**/*.js',
		'!utils/*',
		'!mocks/**/*.js',
		'!.webpack/**/*.*',
		'!models/*',
		'!scripts/*',
		'!migrations/*',
		'!seeders/*',
		'!db/**/*.js',
		'!src/**/*.js',
		'!utils/middleWares/*.js',
		'!services/cognito/*.js',
		'!aws/*js',
	],
	coverageThreshold: {
		global: {
			statements: 40,
			branches: 40,
			functions: 40,
			lines: 40,
		},
	},
	moduleNameMapper: {
		'@(utils|services)(.*)$': '<rootDir>/$1/$2',
		'@mocks(.*)$': '<rootDir>/__mocks__/$1',
		'@daos(.*)$': '<rootDir>/daos/$1',
		'@models(.*)$': '<rootDir>/models/$1',
	},
};
