service:
  name: ${env:NAME}
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  timeout: ${env:TIMEOUT_SECONDS}
  runtime: nodejs14.x
  stage: ${env:STAGE}
  region: ${env:REGION}
  versionFunctions: false
package:
  individually: true
custom:
  urlPrefix: 'sls'
  webpack:
    includeModules: true
functions: ${file(./resources/lambda/functions.yml)}
resources:
  - ${file(./resources/config/roles.yml)}
  - ${file(./resources/config/rds.yml)}