service: ${env:NAME}
useDotenv: true
variablesResolutionMode: 20210326

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  timeout: ${env:TIMEOUT_SECONDS}
  runtime: nodejs14.x
  region: ${env:REGION}
  versionFunctions: false
package:
  individually: true
custom:
  webpack:
    includeModules:
      forceExclude:
        - '@aws-sdk/client-sqs'
    packager: 'pnpm'
  AURORA:
    VPC_CIDR: 10
functions: ${file(./resources/lambda/functions.yml)}
resources:
  - ${file(./resources/config/roles.yml)}
  - ${file(./resources/config/vpc.yml)}
  - ${file(./resources/config/subnet.yml)}
  - ${file(./resources/config/internet-gateway.yml)}
  - ${file(./resources/config/nat-gateway.yml)}
  - ${file(./resources/config/elastic-ip.yml)}
  - ${file(./resources/config/route-private.yml)}
  - ${file(./resources/config/security-groups.yml)}
  - ${file(./resources/config/sqs.yml)}
  - ${file(./resources/cognito/cognito.yml)}
  - ${file(./resources/config/rds.yml)}
  # - ${file(./resources/config/route-public.yml)}
