service: ${env:NAME}
useDotenv: true
variablesResolutionMode: 20210326

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  timeout: ${env:TIMEOUT_SECONDS}
  runtime: nodejs14.x
  region: ${env:REGION}
  versionFunctions: false
package:
  individually: true
custom:
  urlPrefix: 'sls'
  webpack:
    includeModules:
      forceExclude:
        - '@aws-sdk/client-sqs'
    packager: 'yarn'
functions: ${file(./resources/lambda/functions.yml)}
resources:
  - ${file(./resources/config/roles.yml)}
  - ${file(./resources/config/rds.yml)}
  - ${file(./resources/config/sqs.yml)}
