Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    DependsOn:
        - LambdaSnsRole
    Properties:
      LambdaConfig:
          PostConfirmation: arn:aws:lambda:${env:REGION}:${env:ACCOUNT_ID}:function:${env:NAME}-${env:STAGE}-postConfirmation
      UserPoolName: sls-todo-${env:STAGE}-user-pool
      AutoVerifiedAttributes:
          - email
      MfaConfiguration: 'OFF'
      UsernameAttributes:
        - email
      EmailConfiguration:
          EmailSendingAccount: DEVELOPER
          ReplyToEmailAddress: ${env:SUPPORT_EMAIL}
          From: ${env:SUPPORT_EMAIL}
          SourceArn: arn:aws:ses:${env:REGION}:${env:ACCOUNT_ID}:identity/${env:SUPPORT_EMAIL}
      EmailVerificationMessage: Your verification code is {####}.
      EmailVerificationSubject: Your verification code
      Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: True
            RequireNumbers: True
            RequireSymbols: True
            RequireUppercase: True
          Schema:
            - Name: email
              AttributeDataType: String
              Mutable: false
              Required: true
            - Name: group
              AttributeDataType: String
              Mutable: true
              Required: false
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ${env:STAGE}-user-pool-client
      GenerateSecret: false
      SupportedIdentityProviders:
          - COGNITO
      CallbackURLs:
          - ${env:CALLBACK_URL}
      LogoutURLs:
          - ${env:LOGOUT_URL}
      DefaultRedirectURI:
          - ${env:REDIRECT_URL}
      AllowedOAuthFlows:
          - implicit
      AllowedOAuthScopes:
          - email
          - openid
          - aws.cognito.signin.user.admin
          - profile
          - phone
      ExplicitAuthFlows:
          - ALLOW_REFRESH_TOKEN_AUTH
          - ALLOW_USER_SRP_AUTH
      AllowedOAuthFlowsUserPoolClient: true
      UserPoolId:
        Ref: CognitoUserPool

  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: slstodoauth-${env:STAGE}
      UserPoolId: 
        Ref CognitoUserPool

Outputs:
    UserPoolId:
      Description: The Id of the CognitoUserPool
      Value: 
        Ref CognitoUserPool
    UserPoolClientId:
      Description: The Id of the UserPoolClientId
      Value: 
        Ref CognitoUserPoolClient