Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      LambdaConfig:
        KMSKeyID:
        CustomSMSSender:
          LambdaArn:
          LambdaVersion: V1_0
        CustomEmailSender:
          LambdaArn:
          LambdaVersion: V1_0
        PostConfirmation:
      UserPoolName: ${self:custom.userPoolName}
      AutoVerifiedAttributes:
        - email
      AliasAttributes:
        - phone_number
      UsernameConfiguration:
        CaseSensitive: ${env:ENABLE_CASE_SENSTIVITY}
      SmsConfiguration:
        ExternalId:
        SnsCallerArn: !GetAtt snsRole.Arn
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: True
          RequireNumbers: True
          RequireSymbols: True
          RequireUppercase: True
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: password
          AttributeDataType: String
          Mutable: true
          Required: false

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient

    Properties:
      ClientName:
      GenerateSecret: false
      AccessTokenValidity: 840
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - ${env:CALLBACK_URL}
      LogoutURLs:
        - ${env:LOGOUT_URL}

      AllowedOAuthFlowsUserPoolClient: true
      UserPoolId: !Ref CognitoUserPool

  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain:
      UserPoolId: !Ref CognitoUserPool
Outputs:
  UserPoolId:
    Description: The Id of the CognitoUserPool
    Value: !Ref CognitoUserPool
  UserPoolClientId:
    Description: The Id of the UserPoolClientId
    Value: !Ref CognitoUserPoolClient
