name: serverless-template-cd

on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      # - uses: pnpm/action-setup@v2
      #   with:
      #     version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: actions/checkout@v3
      - name: Get branch name
        id: vars
        run: echo ::set-output name=stage::${GITHUB_REF#refs/*/}
      - name: Set env.ENVIRONMENT_NAME
        run: |
          if [[ ${{steps.vars.outputs.stage}} == 'dev' ]]; then
              echo "ENVIRONMENT_NAME=dev" >> "$GITHUB_ENV"
          fi
      - name: Setup environment
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Deploy
        run: yarn deploy:dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_MY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_MY }}
