name: serverless-template-cd

on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: yarn/action-setup@v2
        name: Install yarn
        id: yarn-install
        with:
          version: 7
          run_install: false

      - name: Get yarn store directory
        id: yarn-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(yarn store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup yarn cache
        with:
          path: ${{ steps.yarn-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-yarn-store-${{ hashFiles('**/yarn-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-yarn-store-
      - name: Get branch name
        id: vars
        run: echo ::set-output name=stage::${GITHUB_REF#refs/*/}
      - name: Set env.ENVIRONMENT_NAME
        run: |
          if [[ ${{steps.vars.outputs.stage}} == 'dev' ]]; then
              echo "ENVIRONMENT_NAME=dev" >> "$GITHUB_ENV"
          fi
      - name: Install dependencies
        run: yarn i
      # - name: Deploy
      #   run: yarn deploy:dev
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
