name: serverless-template-ci
on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'pnpm'
      - name: install dependencies
        run: pnpm i
      - name: run the lint
        run: pnpm lint
      - name: Test
        run: pnpm test
