name: serverless-template-ci
on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: yarn/action-setup@v2
        name: Install yarn
        id: yarn-install
        with:
          version: 7
          run_install: false

      - name: Get yarn store directory
        id: yarn-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(yarn store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup yarn cache
        with:
          path: ${{ steps.yarn-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-yarn-store-${{ hashFiles('**/yarn-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-yarn-store-
      - name: Install dependencies
        run: yarn i
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
