name: serverless-template-ci
on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: setup the environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Clean Cache
        run: |
          npm cache clean --force
      - name: install dependencies
        run: yarn
      - name: run the lint
        run: yarn lint
      - name: Test
        run: yarn test